# Generated by Django 5.0.1 on 2024-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_customer_seller_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
