# Generated by Django 5.0.1 on 2024-02-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_seller_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
